# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: 
google_analytics: 
title: wack's blog
indexContent: false #在首页是否显示文章详情，true为显示
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: wack

description: Stylish Jekyll Theme
author:
  name: w03k
  email: i.am.wack.1993@gmail.com
  github: imwack 
  twitter: w0_3k
  pinterest: 
  linkedin: 
  bio: Nice to meet you, where you've been?
  email_md5: 3e16476c2a29901c74bad612da8b0f4d

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

#gems:
plugins:
  - jekyll-paginate
#port:5000