# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: 
google_analytics: 
title: wack's blog

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: wack's blog

description: Stylish Jekyll Theme
author:
  name: wack
  email: i.am.wack.1993@gmail.com
  github: imwack 
  twitter: w0_3k
  pinterest: 
  linkedin: 
  bio: Keep calm...
  email_md5: 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
